In [44]:
import numpy as np 
import pandas as pd 
import scipy .stats as stats


import math
np.random.seed(11)
school_ages=stats.poisson.rvs(mu=30,size=2000)
classA_ages=stats.poisson.rvs(mu=35,size=80)

In [45]:
school_ages

array([24, 29, 29, ..., 40, 21, 30], dtype=int64)

In [46]:
classA_ages

array([30, 43, 28, 28, 43, 27, 30, 31, 32, 31, 31, 44, 37, 28, 31, 32, 31,
       35, 35, 26, 32, 38, 42, 36, 50, 31, 46, 36, 31, 36, 38, 29, 34, 35,
       40, 34, 35, 36, 27, 38, 36, 24, 39, 30, 35, 30, 33, 25, 20, 30, 35,
       38, 32, 30, 26, 52, 33, 37, 38, 31, 33, 31, 23, 27, 37, 41, 30, 33,
       38, 36, 37, 40, 38, 18, 40, 33, 42, 43, 43, 24], dtype=int64)

In [47]:
classA_ages.mean()

33.975

In [48]:
import scipy .stats as ttest_1samp

In [49]:
tstatistics,p_value=ttest_1samp(classA_ages,popmean=school_ages.mean())

TypeError: 'module' object is not callable

In [ ]:
if p_value<=0.05:
    print("reject Ho")
else:
    print("accept Ho")

NameError: name 'p_value' is not defined

paired testing

In [ ]:
np.random.seed(10)
classB_ages=stats.poisson.rvs(mu=32,size=60)
classB_ages.mean()

31.05

In [ ]:
_,p_value=stats.ttest_ind(a=classA_ages,b=classB_ages,equal_var=False)
p_value

0.003912598254873628

In [ ]:
if p_value<=0.05:
    print("we are recting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are recting null hypothesis


Chi-square Test

The test is applied when you have two categorical variables from a single population. It is used to determine whether there is a significant association between the two variables.

In [52]:
import scipy.stats as stats

In [51]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset=sns.load_dataset('tips')

In [53]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [55]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [56]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [57]:
#observed values
Observed_values=dataset_table.values
print("observed values:-\n",Observed_values)

observed values:-
 [[60 97]
 [33 54]]


In [59]:
chi2_stats,p_value,dof,expected_values=stats.chi2_contingency(dataset_table)